language: java

jdk:
  - oraclejdk8

install:
  - "true"
  -
script:
  - "google-chrome --version"
  - "./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck dependency:resolve-plugins"
  - "./mvnw -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pokta-tck install"